### PR TITLE
Update QtLocale with CLDR-34 metadata from Q3/2018

### PR DESCRIPTION
**Pull request by Flohack74**
This is a contribution to https://github.com/ubports/ubuntu-touch/issues/655

### CODE REVIEW

**Review by tsimonq2 — CHANGES_REQUESTED** [review]
```
Description: Update of CLDR locale data to v34
 Multiple requests were made to update to a newer locale version of Qt to include more languages
```
This should wrap at 80 characters (with new lines also being indented the same).
```
Origin: http://archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/qtbase-opensource-src_5.9.5+dfsg.orig.tar.xz
Reviewed-by: <name and email of a reviewer, optional>
```
If Reviewed-by isn't filled in, it shouldn't be there.
Additionally, I would try to choose something different for the origin. We're talking about the origin of the patch, not of the original tarball.

**Comment by tsimonq2** [comment]
Technically `Last-Update: 2019-01-10` should now be `Last-Update: 2019-01-11`, but I don't think it will make a difference.

ACK.

**Review by tsimonq2 — APPROVED** [review]

**Comment by jezek** [comment]
how do we make tests, to see, if this bug is solved?

**Comment by Flohack74** [comment]
You can select SC as language from the menu now. However, it lacks translation since its not an official Ubuntu language. But this is another issue...

**Comment by jezek** [comment]
FP2 (2019-W9) - confirmed, there is a Sardinian (Italy) option in Language selection.

**Pull request merged**
